service: sla-monitor-report-sqsworker

# pin to a specific Serverless version
frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  region: ${env:AWS_REGION, 'us-east-1'}
  runtime: nodejs8.10
  deploymentBucket: ${opt:deployBucket}
  stage: live
  logRetentionInDays: 3 # cloudwatch logs
  timeout: 30 # seconds
  versionFunctions: true
  iamRoleStatements:
    -
      Effect: Allow
      Action:
        - sqs:GetQueueUrl
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
      Resource:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:sqs'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - sla-monitor-reports-${env:AWS_ENV, 'dev'}
    -
      Effect: Allow
      Action:
        - cloudwatch:GetMetricData
        - cloudwatch:ListMetrics
      Resource: "*"
    -
      Effect: Allow
      Action:
        - s3:PutObject
      Resource: arn:aws:s3:::sla-monitor-reports-${env:AWS_ENV, 'dev'}-${env:AWS_REGION, 'us-east-1'}/*
      

plugins:
  - serverless-prune-plugin
  - serverless-mocha-plugin

custom:
  # serverless-prune-plugin
  prune:
    automatic: true
    number: 5

package:
  exclude:
    - "**"
  include:
    - node_modules/**
    - package.json
    - package-lock.json
    - events/**
    - src/**
 
functions:
  sla-monitor-report-sqsworker:
    name: 'sla-monitor-report-sqsworker'
    handler: src/index.handler
    environment:
      AWS_ENV: ${env:AWS_ENV, 'dev'}
      METRIC_NAMESPACE: ${env:SLAMONITOR_NAMESPACE, 'SLA-Monitor'}
      REPORTS_SQS_QUEUE_NAME: sla-monitor-reports-${env:AWS_ENV, 'dev'}
      REPORTS_S3_BUCKET_NAME: sla-monitor-reports-${env:AWS_ENV, 'dev'}-${env:AWS_REGION, 'us-east-1'}
      REPORTS_S3_PREFIX: 'slamon/'
      TIME_RANGES: '1d,3d,7d,14d'
      SLARUNNER_S3BUCKETNAME: sla-monitor-runner-logs-${env:AWS_ENV, 'dev'}-${env:AWS_REGION, 'us-east-1'}
      SERVICES_LIST_TTL_SECONDS: 30
      LOG_LEVEL: 'debug'
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - "ProcessSLAReportSQSQueue"
              - "Arn"
          batchSize: 1

resources:
  Resources:
    ProcessSLAReportSQSQueue:
      Type: AWS::SQS::Queue
      Properties: 
        QueueName: sla-monitor-reports-${env:AWS_ENV, 'dev'}
        ReceiveMessageWaitTimeSeconds: 20
        VisibilityTimeout: 30
        MessageRetentionPeriod: 345600 # seconds (4 days)
        RedrivePolicy:
          deadLetterTargetArn: 
            Fn::GetAtt: 
              - "ProcessSLAReportSQSQueueDeadletter"
              - "Arn"
          maxReceiveCount: 2
    ProcessSLAReportSQSQueuePolicy:
      Type: 'AWS::SQS::QueuePolicy'
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Id: sqspolicy
          Statement:
            - Sid: SendMessage-To-Queue-From-SNS-Topic
              Effect: Allow
              Principal: "*"
              Action:
                - 'sqs:SendMessage'
              Resource: { "Fn::Join": [":", ["arn:aws:sqs", { "Ref" : "AWS::Region" }, { "Ref" : "AWS::AccountId" }, "sla-monitor-reports-${env:AWS_ENV, 'dev'}" ] ] }
              Condition:
                ArnEquals:
                  aws:SourceArn: { "Fn::Join" : ["", ["arn:aws:sns:", { "Ref" : "AWS::Region" }, ":", { "Ref" : "AWS::AccountId" }, ":sla-monitor-result-published-${env:AWS_ENV, 'dev'}" ] ] }
        Queues:
          - { "Fn::Join" : ["", ["https://sqs.", { "Ref" : "AWS::Region" }, ".amazonaws.com/", { "Ref" : "AWS::AccountId" }, "/", "sla-monitor-reports-${env:AWS_ENV, 'dev'}" ] ] }
      DependsOn:
        - ProcessSLAReportSQSQueue
    ProcessSLAReportSQSQueueDeadletter:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "sla-monitor-reports-deadletter-${env:AWS_ENV, 'dev'}"
    ProcessSLAReportSNSSubscription:
      DependsOn: ProcessSLAReportSQSQueue
      Type: AWS::SNS::Subscription
      Properties:
        Endpoint: { "Fn::Join" : [":", ["arn:aws:sqs", { "Ref" : "AWS::Region" }, { "Ref" : "AWS::AccountId" }, "sla-monitor-reports-${env:AWS_ENV, 'dev'}" ] ] }
        Protocol: SQS
        TopicArn: { "Fn::Join" : ["", ["arn:aws:sns:", { "Ref" : "AWS::Region" }, ":", { "Ref" : "AWS::AccountId" }, ":sla-monitor-result-published-${env:AWS_ENV, 'dev'}" ] ] }
    SLAReportsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: sla-monitor-reports-${env:AWS_ENV, 'dev'}-${env:AWS_REGION, 'us-east-1'}
        AccessControl: Private
        BucketEncryption:
          ServerSideEncryptionConfiguration:
            -
              ServerSideEncryptionByDefault:
                SSEAlgorithm: AES256
        LifecycleConfiguration:
          Rules:
          - ExpirationInDays: 30
            Status: Enabled
    S3ProxyIAMRole:
      Type: "AWS::IAM::Role"
      Properties:
        RoleName: sla-monitor-reports-s3proxy-${env:AWS_REGION, 'us-east-1'}
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Principal:
                Service:
                  - ecs-tasks.amazonaws.com
                AWS:
                  - 'Fn::Join':
                    - ':'
                    -
                      - 'arn:aws:iam:'
                      - Ref: 'AWS::AccountId'
                      - 'root'
              Action: 
                - "sts:AssumeRole"
        Path: "/"
    S3ProxyIAMPolicy:
      Type: AWS::IAM::Policy
      Properties:
        PolicyName: sla-monitor-reports-s3-proxy-${env:AWS_REGION, 'us-east-1'}
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Action:
                - "s3:ListBucket"
              Resource:
                Fn::GetAtt: [ SLAReportsBucket, Arn ]
            -
              Effect: "Allow"
              Action:
                - "s3:GetObject"
              Resource:
                - 'Fn::Join':
                  - '/'
                  -
                    - Fn::GetAtt: [ SLAReportsBucket, Arn ]
                    - '*'
        Roles:
          - Ref: S3ProxyIAMRole
